[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.mysqli", "php82Packages.composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[phases.build]
cmds = [
  "chmod -R 775 storage bootstrap/cache",
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear"
]

[start]
cmd = "php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT"
